services:
  frontend:
    image: node:20
    container_name: gakuwa-frontend
    working_dir: /app
    volumes:
      - ./apps/frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "${FRONTEND_PORT}:5173"
    depends_on:
      - backend

  backend:
    image: node:20
    container_name: gakuwa-backend
    working_dir: /app
    volumes:
      - ./apps/backend:/app
    command: sh -c "mkdir -p /tmp/avatars && chmod 700 /tmp/avatars && npm install && npm run dev"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_FROM=no-reply@example.com
      - MINIO_ENDPOINT=${MINIO_HOST}
      - MINIO_PORT=${MINIO_API_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    ports:
      - "${BACKEND_PORT}:3000"
      - "5555:5555"  # For debugging with Node Inspector
    depends_on:
      - db
      - mailhog

  db:
    image: mysql:8.0
    container_name: gakuwa-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: gakuwa-mailhog
    ports:
      - "${MAILHOG_WEB_PORT}:8025"   # Web UI â†’ http://localhost:${MAILHOG_WEB_PORT}
      - "${MAILHOG_SMTP_PORT}:1025"  # SMTP

  nginx:
    image: nginx:alpine
    container_name: gakuwa-nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
  minio:
    build:
        context: ./infra/minio
    image: myminio:minio
    container_name: minio
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address :9001
    volumes:
      - ./data/minio-data:/data
    restart: unless-stopped

volumes:
  db-data: